# fly.toml app configuration file generated for blog-back-late-fire-2179 on 2024-02-01T04:00:38+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'blog-back-late-fire-2179'
primary_region = 'mad'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.1'

[env]
  APP_ENV = 'production'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'
  DB_CONNECTION='mysql'
  DB_HOST='aws.connect.psdb.cloud'
  DB_DATABASE='laravel'
  DB_USERNAME='3lc3vfwuq34tglq4fv1i'
  MYSQL_ATTR_SSL_CA='/etc/ssl/certs/ca-certificates.crt'
  JWT_SECRET='sp12f1rd9JIs1Dh1DXnVncSRRgQsbjm4znO3olHutwYyfsV9Nppuxt2pvQKghzFO'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
